# -*- coding: utf-8 -*-
"""液面相对高度检测.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fmHrYZNOMZG22cbHHvcgj7qPmzfak9f-
"""

import torch
from PIL import Image

def load_model(model_path):
    # 加载你的模型和权重
    

def detect_liquid_level(model, image_path, threshold):
    img = Image.open(image_path)

    results = model(img)

    detections = results.pandas().xyxy[0]

    # 搜索检测框
    for tube_type in ['tip-p20-1', 'tip-p20-2', 'tip-p300-1', 'tip-p300-2']:
        tube_detections = detections[detections['name'] == tube_type]
        for _, tube_bbox in tube_detections.iterrows():
            # 初始化距离和匹配液体
            min_distance = float('inf')
            matched_liquid = None

            for liquid_type in ['blue liquid', 'red liquid', 'transparent liquid']:
                liquid_detections = detections[detections['name'] == liquid_type]
                for _, liquid_bbox in liquid_detections.iterrows():
                    # 计算x坐标距离
                    distance = abs((tube_bbox['xmin'] + tube_bbox['xmax']) / 2 - (liquid_bbox['xmin'] + liquid_bbox['xmax']) / 2)
                    
                    # 更新匹配液体
                    if distance < min_distance:
                        min_distance = distance
                        matched_liquid = liquid_bbox
            
            # 计算高度
            if matched_liquid is not None:
                liquid_level = (tube_bbox['ymax'] - matched_liquid['ymin']) / (tube_bbox['ymax'] - tube_bbox['ymin'])
                # 预警
                if liquid_level < threshold:
                    print(f'Warning: Liquid level in {tube_type} is below the threshold! Current level: {liquid_level}')



model = load_model('yolov5.pt')


detect_liquid_level(model, '要检测的图像.jpg', 0.3)